Wrap JPL for scikit-learn. * Make JPL webpageclassifier a SciKit classifier * Refactor more webpageclassifier -> wpc_utils * Move & update test_simple.html * Add URL/HTML data utils: json_merge.py and * Add train.json - has HTML. Still need to use for error categs. * Add Apache license * Create Notebook to test JPL webclass * MANY changes in webclassifier.py, including:   - Refactor much to wpc_utils.py   - Streamline cosine_sim()   - Add UNDEF and ERROR vs 'undecided'   - Use logging module   - Changed various return types for Scikit   - Improved logic for error pages: tries bleaching URL, better logging & tallying   - Uses scikit metrics * In wpc_utils:   - Add bleach(), with doctests   - Better logging   - Tweaks
               precision    recall  f1-score   support

        ERROR       0.00      0.00      0.00         0
    UNDEFINED       0.00      0.00      0.00         0
         blog       0.98      0.63      0.77        63
   classified       0.26      0.06      0.09        89
        forum       0.97      0.57      0.72        54
         news       0.84      0.61      0.70        92
search_engine       0.00      0.00      0.00        81
     shopping       0.35      0.66      0.46        56
         wiki       0.96      0.72      0.82        65

  avg / total       0.59      0.43      0.48       500

Confusion Matrix:
               ERROR: [0 0 0 0 0 0 0 0 0]
           UNDEFINED: [0 0 0 0 0 0 0 0 0]
                blog: [ 1 11 40  1  0  3  0  7  0]
          classified: [ 7 48  0  5  0  0  0 28  1]
               forum: [ 1 14  0  1 31  2  0  5  0]
                news: [ 4 12  1  2  1 56  0 16  0]
       search_engine: [15 45  0  5  0  6  0  9  1]
            shopping: [ 3 12  0  4  0  0  0 37  0]
                wiki: [ 1 12  0  1  0  0  0  4 47]
   µ Info: 0.38
 Accuracy: 0.43
  Total #: 500
#Bleached: 37
  #Errors: 32