* Tweak parallelize: specifying n_jobs; use numpy vs pandas. * Modify error.txt to improve performance.
Showing 3x speedup on 8 cores -- pandas might be faster?
Improved 'error' classification, but still much worse than thh's SVM.
  - Emphasized words found often in error pages
  - Reduced if found in forum & shopping, which were getting confused
  - Great precision, poor recall (21 of 240 found)

INFO:root:Creating JPL classifier
INFO:root:Classifier 'training' completed.
INFO:root:TIMING: n_jobs = 8, t = 14:26:22, dt = **49.267s**
N = 1106
             precision    recall  f1-score   support

       blog       0.82      0.54      0.65        69
       wiki       0.84      0.85      0.84        79
       news       0.86      0.44      0.59       151
      forum       0.77      0.80      0.78       337
 classified       0.44      0.28      0.34        75
   shopping       0.52      0.70      0.60       155
  UNCERTAIN       0.00      0.00      0.00         0
      error       0.95      0.09      0.16       240

avg / total       0.77      0.54      0.56      1106

Confusion Matrix:
                blog:   37,   0,   1,   3,   4,   9,  15,   0
                wiki:    0,  67,   0,   2,   0,   3,   7,   0
                news:    0,   6,  67,  10,  10,  30,  28,   0
               forum:    1,   0,   1, 271,   4,  12,  47,   1
          classified:    0,   0,   0,   0,  21,  31,  23,   0
            shopping:    0,   0,   1,   0,   8, 109,  37,   0
           UNCERTAIN:    0,   0,   0,   0,   0,   0,   0,   0
               error:    7,   7,   8,  68,   1,  16, 112,  21

   µ Info: 0.40
   Total #: 1106
#Predicted: 1106
  Accuracy: 0.54